// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {trackingserver} from '../models';
import {torrent} from '../models';
import {backend} from '../models';

export function CreateTorrentFile(arg1:string):Promise<Array<number>>;

export function DownloadFromSeeders(arg1:Array<trackingserver.Peer>,arg2:torrent.Torrent,arg3:number):Promise<void>;

export function GeneratePeerID():Promise<string>;

export function HashInfo(arg1:torrent.Torrent):Promise<Array<number>>;

export function ReadFileToBytes(arg1:string):Promise<Array<number>>;

export function SaveFileFromBytes(arg1:Array<number>,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectAnyFile():Promise<backend.FileInfo>;

export function SelectTorrentFile():Promise<backend.FileInfo>;

export function SendTrackerRequest(arg1:torrent.Torrent,arg2:string):Promise<Array<trackingserver.Peer>>;

export function UnmarshalTorrent(arg1:Array<number>):Promise<torrent.Torrent>;
