// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTorrentFile(arg1) {
  return window['go']['main']['App']['CreateTorrentFile'](arg1);
}

export function DownloadFromSeeders(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFromSeeders'](arg1, arg2, arg3, arg4);
}

export function GeneratePeerID() {
  return window['go']['main']['App']['GeneratePeerID']();
}

export function HashInfo(arg1) {
  return window['go']['main']['App']['HashInfo'](arg1);
}

export function ReadFileToBytes(arg1) {
  return window['go']['main']['App']['ReadFileToBytes'](arg1);
}

export function SaveFileFromBytes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileFromBytes'](arg1, arg2, arg3, arg4);
}

export function SelectAnyFile() {
  return window['go']['main']['App']['SelectAnyFile']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}

export function SendTrackerRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTrackerRequest'](arg1, arg2, arg3);
}

export function UnmarshalTorrent(arg1) {
  return window['go']['main']['App']['UnmarshalTorrent'](arg1);
}
