// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFileToBytes(arg1) {
  return window['go']['main']['App']['ReadFileToBytes'](arg1);
}

export function SelectAnyFile() {
  return window['go']['main']['App']['SelectAnyFile']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}

export function UnmarshalTorrent(arg1) {
  return window['go']['main']['App']['UnmarshalTorrent'](arg1);
}
