// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function HashInfo(arg1:string):Promise<string>;

export function ReadFileToBytes(arg1:string):Promise<Array<number>>;

export function SelectAnyFile():Promise<backend.FileInfo>;

export function SelectTorrentFile():Promise<backend.FileInfo>;

export function SendTrackerRequest(arg1:any,arg2:string):Promise<Array<number>>;

export function UnmarshalTorrent(arg1:Array<number>):Promise<any>;
